#!/usr/bin/env python3
"""Generate an mdBook SUMMARY.md for one manual from its curated index.md.

manuals/<app>/index.md is a hand-ordered nested bullet list that mirrors the
original help site's sidebar:

    - **Chapter name**
      - [Page title](content/NN-chapter/NN-page.md)

mdBook wants:

    # Chapter name
    - [Page title](content/NN-chapter/NN-page.md)

Usage:
    scripts/gen_summary.py <app>            # write manuals/<app>/SUMMARY.md
    scripts/gen_summary.py <app> --list     # print ordered .md paths, one per line
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

BOLD_HEADER = re.compile(r"^\s*[-*]\s+\*\*(.+?)\*\*\s*$")
LINK_LINE = re.compile(r"^\s*[-*]\s+\[(?P<text>[^\]]+)\]\((?P<href>[^)]+?\.md)\)\s*(?P<tail>.*)$")


def parse(index_md: Path):
    """Yield ('header', title) and ('page', text, href) tuples in document order."""
    seen: set[str] = set()
    for raw in index_md.read_text(encoding="utf-8").splitlines():
        m = BOLD_HEADER.match(raw)
        if m:
            yield ("header", m.group(1).strip())
            continue
        m = LINK_LINE.match(raw)
        if m:
            href = m.group("href").strip()
            # Skip explicit "see above" duplicate pointers and any repeat target.
            if "see above" in m.group("tail").lower():
                continue
            if href in seen:
                continue
            seen.add(href)
            yield ("page", m.group("text").strip(), href)


def build_summary(app: str) -> str:
    manual = ROOT / "manuals" / app
    items = list(parse(manual / "index.md"))
    out = ["<!-- generated by scripts/gen_summary.py - do not edit by hand -->", "", "# Summary", ""]
    if (manual / "index.md").exists():
        out += ["[Introduction](index.md)", ""]
    for item in items:
        if item[0] == "header":
            out += ["", f"# {item[1]}", ""]
        else:
            _, text, href = item
            target = (manual / href)
            if not target.exists():
                print(f"  warning: {app}: SUMMARY entry points at missing file: {href}", file=sys.stderr)
            out.append(f"- [{text}]({href})")
    return "\n".join(out).rstrip() + "\n"


def ordered_files(app: str):
    manual = ROOT / "manuals" / app
    paths = ["index.md"] if (manual / "index.md").exists() else []
    for item in parse(manual / "index.md"):
        if item[0] == "page":
            paths.append(item[2])
    return paths


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__)
        return 2
    app = argv[0]
    manual = ROOT / "manuals" / app
    if not (manual / "index.md").exists():
        print(f"no manuals/{app}/index.md - nothing to do", file=sys.stderr)
        return 1
    if "--list" in argv[1:]:
        print("\n".join(ordered_files(app)))
        return 0
    dest = manual / "SUMMARY.md"
    dest.write_text(build_summary(app), encoding="utf-8")
    n = sum(1 for _ in parse(manual / "index.md") if _[0] == "page")
    print(f"wrote {dest.relative_to(ROOT)} ({n} pages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
